cnblog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from blog import views
from django.views.static import serve
from  cnblog import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'login/', views.login),
    re_path(r'get_validCode_img/', views.get_validCode_img),
    re_path(r'index/$', views.index),
    re_path(r'register/', views.register),
    re_path(r'login_out/', views.login_out),
    # media配置
    re_path(r"media/(?P<path>.*)$",serve,{"document_root":settings.MEDIA_ROOT}),
    # 个人站点的路由配置
    re_path(r"index/(?P<username>\w+)/$",views.home_site),
    # 个人站点的url
    re_path(r"index/(?P<username>\w+)/(?P<condition>tag|category|archive)/(?P<parm>.*)/$",views.home_site),
    # 个人文章详情页
    re_path(r"index/(?P<username>\w+)/articles/(?P<article_id>\d+)/$",views.article_deatile),
    re_path(r"diggt/",views.diggt),
    re_path(r"content/",views.content),
    re_path(r"get_conment_tree/",views.get_conment_tree),
]

blog/models.py
from django.db import models

# Create your models here.


from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to='avatars/', default="/avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.OneToOneField(to='Blog', to_field='nid', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.TextField()

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', to_field='nid', null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    """
    点赞表
    """

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """

    评论表

    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

templates/article_deatile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
    </style>
</head>
<body>
{% extends "base.html" %}
{% block content %}
    {% csrf_token %}
    <h2 class="text-center">{{ article_obj.title }}</h2>
    <div class="cont">
        {{ article_obj.content|safe }}
    </div>
    <div class="clearfix">
        <div id="div_digg">
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
            </div>
            <div class="buryit action">
                <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
            </div>
            <div class="diggword pull-right" id="digg_tips" style="color: #ff0000;"></div>
        </div>
    </div>

    <div class="conment_list">
    <p class="comment_tree">评论树</p>


    </div>




    <ul class="list-group conment_list">
        <p>评论列表</p>
        {% for comment in comment_obj %}
            <li class="list-group-item">
                <div>
                    <a href="">#{{ forloop.counter }}楼</a>&nbsp;&nbsp;

                    <span class="date_str">{{ comment.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                    <a href="">{{ comment.user.username }}</a>
                    <a class="pull-right replay_dis" username="{{ comment.user.username }}"
                       comment_id="{{ comment.pk }}">回复</a>
                </div>
                <div class="comment_con">
                    {% if comment.parent_comment.pk %}
                        <div class="prarent_pl well">
                            <span class="paren_name_span"
                                  paren_name_span_sx="{{ comment.parent_comment.user.username }}">{{ comment.parent_comment.user.username }}</span>:<span
                                class="parent_content_span"
                                parent_content_span_sx="{{ comment.parent_comment.content }}">{{ comment.parent_comment.content }}</span>
                        </div>
                    {% endif %}
                    <p>{{ comment.content }}</p>
                </div>

            </li>
        {% endfor %}
    </ul>

    <div class="content">
        <p>发表评论</p>
        <p>昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                     value="{{ request.user.username }}">
        </p>
        <p>评论内容:</p>
        <textarea name="" id="comment_content" cols="60" rows="10"></textarea>
        <p>
            <button class="btn btn-default comment_btn">提交评论</button>
        </p>

    </div>


    <script>
        // 点赞请求
        $("#div_digg .action").click(function () {
            $obj = $(this).children("span")
            var is_up = $(this).hasClass("diggit");
            $.ajax({
                url: "/diggt/",
                type: "post",
                data: {
                    "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                    "is_up": is_up,
                    "article_id":{{ article_obj.pk }}

                },
                success: function (data) {
                    {#data=JSON.stringify(data)#}
                    data = JSON.parse(data)
                    if (data.state) {
                        var dig = parseInt($obj.text())
                        $obj.text(dig + 1)
                    } else {
                        if (data.handle) {
                            $("#digg_tips").html("你已经支持过了，thanks!!")
                        } else {
                            $("#digg_tips").html("你已经倒赞过了，下次别来了，thanks!!")
                        }
                    }


                    setTimeout(function () {
                        $("#digg_tips").html("")
                    }, 3000)

                }
            })


        })

        // 评论树
            $.ajax({
                url:"get_conment_tree",
                type:"get",
                data:{"article_id":"{{ article_obj.pk }}"},
                success:function (data) {
                        data=JSON.parse(data)
                        console.log(data)
                    $.each(data,function (index,comment_obj) {
                        var coment_content=comment_obj.content
                        var parent_id=comment_obj.parent_comment_id
                        var nid=comment_obj.nid
                        s= '<div coment_id='+nid+'> <span>'+coment_content+'</span> </div>'
                        if (! parent_id){
                            $(".comment_tree").append(s)
                        }else {
                            $("[coment_id=" + parent_id + "]").append(s);
                        }
                    })

                }

        })


        // 评论功能
        var pid = "";
        $(".comment_btn").click(function () {
            var content = $("#comment_content").val()
            if (pid) {
                var index = content.indexOf("\n");
                content = content.slice(index + 1)
                {#console.log(content)#}
            }

            $.ajax({
                url: "/content/",
                type: "post",
                data: {
                    "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                    "article_id": {{ article_obj.pk }},
                    "content": content,
                    "pid": pid

                },
                success: function (data) {
                    data = JSON.parse(data)
                    {#console.log(data)#}
                    $("#comment_content").val("");
                    pid = "";
                    var create_time = data.create_time
                    var username = data.username
                    var content = data.content
                    var s = `
                    <li class="list-group-item">
                <div>
                    <span class="date_str">${create_time}</span>&nbsp;&nbsp;
                    <a href="">${username}</a>
                </div>
                <div class="comment_con">
                    <p>${content}</p>
                </div>
            </li>
                    `

                    var parent_name = data.parent_name
                    var parent_content = data.parent_content
                    var parent_comment_id = data.parent_pk
                    var z_pl = `
                        <div class="comment_con">

                       <div class="prarent_pl well">
                       ${parent_name}:${parent_content}
                       </div>

                    <p>${content}</p>
                </div>
                    `
                    if (parent_comment_id) {
                        $("ul.conment_list").append(z_pl)
                    } else {
                        $("ul.conment_list").append(s)
                        {#console.log($(".prarent_pl").val())#}
                    }


                }
            })
        })

        $(".replay_dis").click(function () {
            $("#comment_content").focus();
            var ss = "@" + $(".replay_dis").attr("username") + "\n";
            $("#comment_content").val(ss);
            pid = $(this).attr("comment_id")

        })


    </script>

{% endblock %}

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home_site</title>
{#    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>#}
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/blog/dist/css/bootstrap.css">
    <script src="/static/blog/dist/js/bootstrap.min.js"></script>
    <script src="/static/blog/dist/jQuery3.6.0.js"></script>
    <link rel="stylesheet" href="/static/blog/dist/css/home_site.css">
    <link rel="stylesheet" href="/static/blog/dist/css/article_detail.css">
</head>
<body>

<div class="header">
    <div class="content">
        <p class="title">
            <span>{{ blog.title }}</span>
            <a href="" class="backend">管理</a>
        </p>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
                  <div class="panel panel-danger">
                <div class="panel-heading">我的标签</div>
                <div class="panel-body">
                    {% for tag in tag_title_num %}
                        <p><a href="http://127.0.0.1:8000/index/{{ username }}/tag/{{ tag.0 }}/">{{ tag.0 }}({{ tag.1 }})</a></p>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading">我的随笔</div>
                <div class="panel-body">
                    {% for cate in blog_category_num %}
                        <p><a href="http://127.0.0.1:8000/index/{{ username }}/category/{{ cate.title }}/">{{ cate.title }}({{ cate.c }})</a></p>
                    {% endfor %}

                </div>
            </div>

                    <div class="panel panel-success">
                <div class="panel-heading">随笔归档</div>
                <div class="panel-body">
                    {% for date in date_title_num %}
                        <p><a href="http://127.0.0.1:8000/index/{{ username }}/archive/{{ date.0 }}/">{{ date.0 }}({{ date.1 }})</a></p>
                    {% endfor %}

                </div>
            </div>
        </div>
        <div class="col-md-9 clearfix">
            {% block  content %}

            {% endblock %}


        </div>
    </div>
</div>

</body>
</html>

templates/classification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div>
                <div class="panel panel-danger">
                <div class="panel-heading">我的标签</div>
                <div class="panel-body">
                    {% for tag in tag_title_num %}
                        <p><a href="http://127.0.0.1:8000/index/{{ username }}/tag/{{ tag.0 }}/">{{ tag.0 }}({{ tag.1 }})</a></p>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading">我的随笔</div>
                <div class="panel-body">
                    {% for cate in blog_category_num %}
                        <p><a href="http://127.0.0.1:8000/index/{{ username }}/category/{{ cate.title }}/">{{ cate.title }}({{ cate.c }})</a></p>
                    {% endfor %}

                </div>
            </div>

                    <div class="panel panel-success">
                <div class="panel-heading">随笔归档</div>
                <div class="panel-body">
                    {% for date in date_title_num %}
                        <p><a href="http://127.0.0.1:8000/index/{{ username }}/archive/{{ date.0 }}/">{{ date.0 }}({{ date.1 }})</a></p>
                    {% endfor %}

                </div>
            </div>

</div>

</body>
</html>

templates/home_site.html
{% extends "base.html" %}

{% block content %}

{% for article in article_list %}
                <div>
                    <h3><a href="">{{ article.title }}</a></h3>
                </div>
                <div class="article_img">
                <span class="media-right">
                    {{ article.desc }}
                </span>
                </div>
                <div class="small article_num pull-right">
                    <span>发布于&nbsp&nbsp{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp&nbsp
                    <span class="glyphicon glyphicon-comment comment_article">评论({{ article.comment_count }})</span>&nbsp&nbsp
                    <span class="glyphicon glyphicon-thumbs-up down_article">点赞({{ article.down_count }})</span>


                </div>


            {% endfor %}

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/blog/dist/css/bootstrap.css">
    <script src="/static/blog/dist/js/bootstrap.min.js"></script>
    <script src="/static/blog/dist/jQuery3.6.0.js"></script>

    <style>
        #user_actar{
            font-size: 18px;
            margin-right: 10px;
            vertical-align: -3px;
        }

        .article_num{
            margin-top: 10px;

        }
        .comment_article,.down_article{
            vertical-align: -1px;
        }

    </style>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">博客园</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">随笔</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">订阅<span class="sr-only">(current)</span></a></li>
        <li><a href="#">博文</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user" id="user_actar"></span>{{ request.user.username }}</a></li>
        <li class="dropdown">
            {% if request.user.username %}
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>
                <ul class="dropdown-menu">
            <li><a href="#">修改密码</a></li>
            <li><a href="#">修改头像</a></li>
            <li><a href="/login_out/">退出登录</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">小黄书</a></li>
          </ul>
                {% else %}
                <li><a href="/login/">登录</a></li>
                <li><a href="/register/">注册</a></li>

            {% endif %}
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
        <div class="panel panel-info">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

            <div class="panel panel-warning">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>
        </div>
        <div class="col-md-6">
            {% for article in article_obj %}
                <div>
                <h3><a href="">{{ article.title }}</a></h3>
                </div>
             <div class="article_img">
                 <span class="media-left"><a href=""><img src="/media/{{ article.user.avatar }}" alt="" width="57px" height="57px" ></a></span>
                <span class="media-right">
                    {{ article.desc }}
                </span>
             </div>
                <div class="small article_num">
                    <span><a href="">{{ article.user.username }}</a></span>&nbsp&nbsp&nbsp
                    <span>发布于&nbsp&nbsp{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp&nbsp
                    <span class="glyphicon glyphicon-comment comment_article">评论({{ article.comment_count}})</span>&nbsp&nbsp
                    <span class="glyphicon glyphicon-thumbs-up down_article">点赞({{ article.down_count }})</span>



                </div>


            {% endfor %}





        </div>
        <div class="col-md-3">
            <div class="panel panel-info">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

            <div class="panel panel-warning">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    Panel content
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

        </div>

    </div>

</div>


</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/blog/dist/css/bootstrap.css">
    <script src="/static/blog/dist/js/bootstrap.min.js"></script>
    <script src="/static/blog/dist/jQuery3.6.0.js"></script>

</head>
<body>
<h2>登录页面</h2>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="user">用户名</label>
                    <input type="text" ID="user" class="form-control">
                </div>
                <div class="form-group">
                    <label for="pwd">密码</label>
                    <input type="password" id="pwd" class="form-control">
                </div>
                <div class="form-group">
                    <label for="vid">验证码：</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" id="vid" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <img width="270" height="40" src="/get_validCode_img/" alt="" id="random_img">

                        </div>
                    </div>
                </div>
                <input type="button" value="submit" class="btn btn-primary login_btn"><span class="error"></span>
                <a href="/register/" class="btn btn-danger pull-right">注册</a>

            </form>


        </div>


    </div>


</div>

<script>
    // 刷新验证码
    $("#random_img").click(function () {
        $(this)[0].src += "?"
    });
    // 登陆验证
    $(".login_btn").click(function () {
        $.ajax({
            url: "/login/",
            type: "post",
            data: {
                user: $("#user").val(),
                pwd: $("#pwd").val(),
                vid: $("#vid").val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
            },
            success: function (data) {
                console.log(data)
                if (data.user){
                    location.href="/index/"
                }
                else {
                    $(".error").text(data.msg).css({"color":"red","margin-left":10})
                    setTimeout(function () {
                        $(".error").text("")
                    },2000)
                }


            }
        })
    })


</script>
</body>
</html>

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<h2>该网站页面未找到！！！！</h2>


<h3>修复好了bug</h3>
<h1>走错地方了，网页丢失！！（bug修复）</h1>
<h2>开发商城项目100%</h2>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/blog/dist/css/bootstrap.css">
    <script src="/static/blog/dist/js/bootstrap.min.js"></script>
    <script src="/static/blog/dist/jQuery3.6.0.js"></script>

    <style>
        #via_img {
            width: 60px;
            height: 60px;
        }

        #via {
            display: none;
        }

        .via_img {

            margin-left: 20px;
        }

        #span_error {
            color: red;
        }

    </style>

</head>
<body>
<h2>注册页面</h2>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form id="form">
                <form id="form">
                    {% csrf_token %}
                    {% for filed in form %}
                        <div class="form-group">
                            <label for={{ filed.auto_id }}>{{ filed.label }}</label>
                            {{ filed }} <span id="span_error" class="pull-right"></span>
                        </div>

                    {% endfor %}
                    <div class="form-group">
                        <label for="via">头像
                            <img id="via_img" src="/static/blog/img/1.jpg" alt="就问你帅不帅！！！">
                        </label>
                        <input type="file" id="via">
                    </div>
                </form>

                <input type="button" value="submit" class="btn btn-primary register_btn"><span class="error"></span>


            </form>


        </div>


    </div>


</div>

<script>
    // 图片上传
    {#1.获取文件对象#}
    $("#via").change(
        function () {
            var via_obj = $(this)[0].files[0]

            {#2.获取文件路径#}
            reader = new FileReader();
            reader.readAsDataURL(via_obj);
            {#3.修改SRC的属性#}
            reader.onload = function () {
                $("#via_img").attr("src", reader.result)
            }

        }
    )
    // ajax 数据提交

    $(".register_btn").click(function () {
        {#console.log($("#form").serializeArray())#}

        request_data = $("#form").serializeArray()
        var form_data = new FormData();
        $.each(request_data, function (index, data) {

            form_data.append(data.name, data.value)
        })
        {#form_data.append("user", $("#id_user").val());#}
        {#form_data.append("pwd", $("#id_pwd").val());#}
        {#form_data.append("re_pwd", $("#id_re_pwd").val());#}
        {#form_data.append("email", $("#id_email").val());#}
        {#form_data.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val())#}

        form_data.append("via", $("#via")[0].files[0]);
        $.ajax({
            url: "/register/",
            type: "post",
            contentType: false,
            processData: false,
            data: form_data,
            success: function (data) {
                {#console.log(data)#}
                if (data.user) {
                    location.href="/login/"
                } else {
                    msg_error = data["msg"];
                    // 清空错误信息
                    $("#span_error").html("");
                    $(".form-group").removeClass("has-error")
                    $("#id_re_pwd").next().html("")
                    // 展示填写的错误信息
                    $.each(msg_error, function (field, error_list) {
                        {#console.log(field,error_list)#}
                        if(field=="__all__"){
                            $("#id_re_pwd").next().html(error_list[0])
                        }
                        $("#id_" + field).next().html(error_list[0])
                        $("#id_"+ field).parent().addClass("has-error")
                    })
                }

            }
        })


    })


</script>
</body>
</html>